const {ok, throws} = require('assert')
const Stack = require('../lib/stack')
const {logP} = require('../lib/utils/logger')
const {bucketExists, codeExists, lambdaExists, roleExists, not, config, loose} = require('./utils')
const delay = require('delay')

test('stack', () => {
  test.timeout('creates and deletes stack', (done) => {
    Promise.resolve()
    .then(() => loose(Stack.destroy(config)))
    .then(() => not(bucketExists(config)))
    .then(exists => ok(exists))
    .then(() => not(codeExists(config)))
    .then(exists => ok(exists))
    .then(() => not(lambdaExists(config)))
    .then(exists => ok(exists))
    .then(() => not(roleExists(config)))
    .then(exists => ok(exists))
    .then(() => Stack.create(config))
    .then(delay(5000))
    .then(logP('-> bucket exists'))
    .then(() => bucketExists(config))
    .then(exists => ok(exists))
    .then(logP('-> code exists'))
    .then(() => codeExists(config))
    .then(exists => ok(exists))
    .then(logP('-> lambda exists'))
    .then(() => lambdaExists(config))
    .then(exists => ok(exists))
    .then(logP('-> role exists'))
    .then(() => roleExists(config))
    .then(exists => ok(exists))
    .then(() => done())
    .catch(done)
  }, 90000)

  test('Stack.create throws when options are missing', () => {
    throws(() => Stack.create({}))
  })
  test('Stack.destroy throws when options are missing', () => {
    throws(() => Stack.destroy({}))
  })
})
