const {ok} = require('assert')
const Bucket = require('../../lib/bucket')
const createCode = require('../../lib/tasks/code/create')
const deleteCode = require('../../lib/tasks/code/delete')
const {codeExists, config} = require('../utils')

test('code', () => {
  test.timeout('creates and deletes code', (done) => {
    Bucket.destroy(config).then(() => {}).catch(() => {})
    .then(() => Bucket.create(config))
    .then(() => createCode.run(config))
    .then(() => codeExists(config))
    .then(exists => ok(exists))
    .then(() => deleteCode.run(config))
    .then(() => codeExists(config))
    .then(exists => ok(!exists))
    .then(() => done())
    .catch(done)
  }, 30000)
})
