#!/usr/bin/env node

const {run} = require('../lib/tasks/lambda/create')
const {lambdaName, bucketName, roleName} = process.env.OBJECT_KEY || 'sentinel-code.js.zip'
const {success, failure} = require('../lib/utils/command-logger')

run({lambdaName, bucketName, roleName})
.then(() => success(`-> successfully created lambda: "${lambdaName}"`))
.catch(err => failure(`-> failed to create lambda: "${lambdaName}"\n${err.message}`))
