#!/usr/bin/env node

const Bucket = require('../lib/bucket')
const config = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Bucket.create(config)
.then(() => success(`-> successfully created bucket: "${bucketName}"`))
.catch(err => failure(`-> failed to create bucket: "${bucketName}"\n${err.message}`))
