#!/usr/bin/env node

const Stack = require('../lib/stack')
const options = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Stack.create(options)
.then(() => success(`-> successfully created stack!`))
.catch((err) => failure(`-> failed to create stack\n${err.message}`))
