#!/usr/bin/env node

const config = require('../config')
Code.createZip(config)
.then(() => console.log(`successfully created code zip`))
.catch(err => console.error(`failed to create code zip:"\n${err.message}`))
