#!/usr/bin/env node

const {run} = require('../lib/tasks/code/create-zip')

run({})
.then(() => console.log(`successfully created code zip`))
.catch(err => console.error(`failed to create code zip:"\n${err.message}`))
