#!/usr/bin/env node
'use strict'

const {run} = require('./tasks/create-code')
const {bucketName, objectKey} = require('./config')

run({bucketName, objectKey})
.then(() => console.log(`successfully created code in bucket: "${bucketName}"`))
.catch(err => console.error(`failed to create code in bucket: "${bucketName}"\n${err.stack}`))
