#!/usr/bin/env node

const {run} = require('../lib/tasks/create-role')
const {roleName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({roleName})
.then(data => {
  success(`-> successfully created role: "${roleName}"`)
  success(`-> arn: \n\t${data.Role.Arn}`)
})
.catch(err => failure(`-> failed to create role: "${roleName}"\n${err.message}`))
