#!/usr/bin/env node

const {run} = require('../lib/tasks/create-bucket')
const {bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({bucketName})
.then(() => success(`-> successfully created bucket: "${bucketName}"`))
.catch(err => failure(`-> failed to create bucket: "${bucketName}"\n${err.message}`))
