#!/usr/bin/env node

const {run} = require('../lib/tasks/delete-bucket')
const {bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({bucketName})
.then(() => success(`-> successfully deleted bucket: "${bucketName}"`))
.catch(err => failure(`-> failed to delete bucket: "${bucketName}"\n${err.message}`))
