#!/usr/bin/env node

const {run} = require('../lib/tasks/stack/delete')
const options = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run(options)
.then(() => success(`-> successfully deleted stack`))
.catch(err => failure(`-> failed to delete stack\n${err.message}`))
