#!/usr/bin/env node

const {run} = require('../lib/tasks/code/delete')
const {bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({bucketName})
.then(() => success(`-> deleted code`))
.catch(err => failure(`-> failed to delete code: "${bucketName}/sentinel.zip"\n${err.message}`))
