#!/usr/bin/env node

const {run} = require('../lib/tasks/delete-code')
const {bucketName, objectKey} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({bucketName, objectKey})
.then(() => success(`-> deleted code`))
.catch(err => failure(`-> failed to delete code: "${bucketName}/${objectKey}"\n${err.message}`))
