#!/usr/bin/env node

const Lambda = require('../lib/lambda')
const {lambdaName, bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Lambda.destroy({lambdaName, bucketName})
.then(() => success(`-> successfully deleted lambda: "${lambdaName}"`))
.catch(err => failure(`-> failed to delete lambda: "${lambdaName}"\n${err.message}`))
