#!/usr/bin/env node

const {run} = require('../lib/tasks/delete-lambda')
const {lambdaName, bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({lambdaName, bucketName})
.then(() => success(`-> successfully deleted lambda: "${lambdaName}"`))
.catch(err => failure(`-> failed to delete lambda: "${lambdaName}"\n${err.message}`))
