#!/usr/bin/env node

const Role = require('../lib/role')
const roleName = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Role.destroy({roleName})
.then(data => success(`-> successfully deleted role: "${roleName}"`))
.catch(err => failure(`-> failed to delete role: "${roleName}"\n${err.message}`))
