#!/usr/bin/env node

const Bucket = require('../lib/bucket')
const {bucketName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Bucket.destroy({bucketName})
.then(() => success(`-> successfully deleted bucket: "${bucketName}"`))
.catch(err => failure(`-> failed to delete bucket: "${bucketName}"\n${err.message}`))
