#!/usr/bin/env node
'use strict'

const {run} = require('./tasks/delete-role')
const roleName = process.env.ROLE_NAME || 'sentinel-role'

run({roleName})
.then(data => console.log(`successfully deleted role: "${roleName}"`))
.catch(err => console.error(`failed to delete role: "${roleName}"\n${err.stack}`))
