#!/usr/bin/env node

const Stack = require('../lib/stack')
const options = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Stack.destroy(options)
.then(() => success(`-> successfully deleted stack`))
.catch(err => failure(`-> failed to delete stack\n${err.message}`))
