#!/usr/bin/env node

const {run} = require('../lib/tasks/role/delete')
const roleName = process.env.ROLE_NAME || 'sentinel-role'
const {success, failure} = require('../lib/utils/command-logger')

run({roleName})
.then(data => success(`-> successfully deleted role: "${roleName}"`))
.catch(err => failure(`-> failed to delete role: "${roleName}"\n${err.message}`))
