#!/usr/bin/env node

const Lambda = require('../lib/lambda')
const {lambdaName, bucketName, roleName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

Lambda.update({lambdaName, bucketName, roleName})
.then(() => success(`-> successfully updated lambda: "${lambdaName}"`))
.catch(err => failure(`-> failed to update lambda: "${lambdaName}"\n${err.message}`))
