#!/usr/bin/env node

const {run} = require('../lib/tasks/lambda/update')
const {lambdaName, bucketName, roleName} = require('../config')
const {success, failure} = require('../lib/utils/command-logger')

run({lambdaName, bucketName, roleName})
.then(() => success(`-> successfully updated lambda: "${lambdaName}"`))
.catch(err => failure(`-> failed to update lambda: "${lambdaName}"\n${err.message}`))
